import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'bn' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'app.name': 'Al-Yamen BMS',
    // Nav
    'nav.dashboard': 'Dashboard',
    'nav.customers': 'Customers',
    'nav.sales': 'Sales',
    'nav.suppliers': 'Suppliers',
    'nav.purchases': 'Purchases',
    'nav.products': 'Products',
    'nav.hr': 'Human Resources',
    'nav.employees': 'Employees',
    'nav.attendance': 'Attendance',
    'nav.payroll': 'Payroll',
    'nav.accounting': 'Accounting',
    'nav.reports': 'Reports',
    'nav.logout': 'Logout',
    'nav.my_account': 'My Account',
    // Common
    'common.search': 'Search...',
    'common.add': 'Add New',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.loading': 'Loading...',
    'common.actions': 'Actions',
    'common.saving': 'Saving...',
    'common.name': 'Name',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.address': 'Address',
    'common.date': 'Date',
    'common.status': 'Status',
    'common.notes': 'Notes',
    'common.amount': 'Amount',
    'common.total': 'Total',
    'common.balance': 'Balance',
    'common.joined': 'Joined',
    'common.contact': 'Contact',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.deleted': 'Deleted',
    'common.no_data': 'No data found.',
    'common.all': 'All',
    'common.none': '—',
    'common.description': 'Description',
    'common.category': 'Category',
    'common.type': 'Type',
    'common.month': 'Month',
    'common.items': 'Items',
    'common.qty': 'Qty',
    'common.unit_price': 'Unit Price',
    'common.salary': 'Salary',
    // Login
    'login.title': 'Welcome Back',
    'login.subtitle': 'Sign in to your account',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.submit': 'Sign In',
    'login.logging_in': 'Logging in...',
    'login.demo_accounts': 'Demo Accounts',
    'login.demo_admin': 'Admin',
    'login.demo_manager': 'Manager',
    'login.demo_cashier': 'Cashier',
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.total_sales': 'Total Sales',
    'dashboard.total_purchases': 'Total Purchases',
    'dashboard.total_customers': 'Total Customers',
    'dashboard.low_stock': 'Low Stock Items',
    'dashboard.recent_activity': 'Recent Activity',
    'dashboard.monthly_overview': 'Monthly Revenue vs Expenses',
    'dashboard.revenue': 'Revenue',
    'dashboard.expenses': 'Expenses',
    // Customers
    'customers.title': 'Customers',
    'customers.add': 'Add Customer',
    'customers.create_title': 'Create New Customer',
    'customers.save': 'Save Customer',
    'customers.search': 'Search customers...',
    'customers.no_data': 'No customers found.',
    'customers.delete_confirm': 'Are you sure you want to delete this customer?',
    'customers.created': 'Customer created',
    'customers.deleted': 'Customer removed successfully',
    // Suppliers
    'suppliers.title': 'Suppliers',
    'suppliers.add': 'Add Supplier',
    'suppliers.create_title': 'Create New Supplier',
    'suppliers.save': 'Save Supplier',
    'suppliers.search': 'Search suppliers...',
    'suppliers.no_data': 'No suppliers found.',
    'suppliers.delete_confirm': 'Are you sure you want to delete this supplier?',
    'suppliers.created': 'Supplier created',
    'suppliers.deleted': 'Supplier removed successfully',
    // Sales
    'sales.title': 'Sales Orders',
    'sales.add': 'New Sale',
    'sales.create_title': 'Create Sales Order',
    'sales.complete': 'Complete Sale',
    'sales.creating': 'Creating...',
    'sales.search': 'Search orders...',
    'sales.no_data': 'No sales orders found.',
    'sales.delete_confirm': 'Are you sure you want to delete this order?',
    'sales.created': 'Sales order created',
    'sales.deleted': 'Sales order removed',
    'sales.customer_name': 'Customer Name',
    'sales.discount': 'Discount',
    'sales.paid_amount': 'Paid Amount',
    'sales.order_number': 'Order #',
    'sales.customer': 'Customer',
    'sales.all_statuses': 'All Statuses',
    'sales.status.pending': 'Pending',
    'sales.status.confirmed': 'Confirmed',
    'sales.status.delivered': 'Delivered',
    'sales.status.cancelled': 'Cancelled',
    'sales.add_item': 'Add Item',
    'sales.product_id': 'Product ID',
    // Purchases
    'purchases.title': 'Purchase Orders',
    'purchases.add': 'New Purchase',
    'purchases.create_title': 'Create Purchase Order',
    'purchases.create_btn': 'Create Order',
    'purchases.creating': 'Creating...',
    'purchases.search': 'Search orders...',
    'purchases.no_data': 'No purchase orders found.',
    'purchases.delete_confirm': 'Are you sure you want to delete this order?',
    'purchases.created': 'Purchase order created',
    'purchases.deleted': 'Purchase order removed',
    'purchases.supplier_name': 'Supplier Name',
    'purchases.paid_amount': 'Paid Amount',
    'purchases.order_number': 'Order #',
    'purchases.supplier': 'Supplier',
    'purchases.all_statuses': 'All Statuses',
    'purchases.status.pending': 'Pending',
    'purchases.status.received': 'Received',
    'purchases.status.cancelled': 'Cancelled',
    'purchases.add_item': 'Add Item',
    'purchases.unit_cost': 'Unit Cost',
    // Products
    'products.title': 'Products & Inventory',
    'products.add': 'Add Product',
    'products.create_title': 'Create New Product',
    'products.save': 'Save Product',
    'products.saving': 'Saving...',
    'products.search': 'Search products...',
    'products.no_data': 'No products found.',
    'products.delete_confirm': 'Are you sure you want to delete this product?',
    'products.created': 'Product created',
    'products.deleted': 'Product removed',
    'products.sku': 'SKU',
    'products.unit': 'Unit (e.g. pcs, kg, box)',
    'products.selling_price': 'Selling Price',
    'products.cost_price': 'Cost Price',
    'products.initial_stock': 'Initial Stock',
    'products.min_stock': 'Min Stock Alert Level',
    'products.product': 'Product',
    'products.price': 'Price',
    'products.stock': 'Stock',
    'products.low': 'Low',
    // Employees
    'employees.title': 'Employees',
    'employees.add': 'Add Employee',
    'employees.create_title': 'New Employee Profile',
    'employees.save': 'Save Employee',
    'employees.saving': 'Saving...',
    'employees.search': 'Search employees...',
    'employees.no_data': 'No employees found.',
    'employees.delete_confirm': 'Are you sure you want to delete this employee?',
    'employees.created': 'Employee created',
    'employees.deleted': 'Employee removed successfully',
    'employees.full_name': 'Full Name',
    'employees.join_date': 'Join Date',
    'employees.department': 'Department',
    'employees.position': 'Position / Role',
    'employees.monthly_salary': 'Monthly Salary',
    'employees.employee': 'Employee',
    'employees.role': 'Role',
    'employees.joined': 'Joined:',
    'employees.status.active': 'Active',
    'employees.status.inactive': 'Inactive',
    // Attendance
    'attendance.title': 'Attendance',
    'attendance.add': 'Mark Attendance',
    'attendance.create_title': 'Record Attendance',
    'attendance.save': 'Save Record',
    'attendance.saving': 'Saving...',
    'attendance.no_data': 'No attendance records found for this month.',
    'attendance.created': 'Attendance recorded',
    'attendance.employee': 'Employee',
    'attendance.select_employee': 'Select employee',
    'attendance.select_status': 'Select status',
    'attendance.check_in': 'Check In Time',
    'attendance.check_out': 'Check Out Time',
    'attendance.status.present': 'Present',
    'attendance.status.absent': 'Absent',
    'attendance.status.late': 'Late',
    'attendance.status.half_day': 'Half Day',
    // Payroll
    'payroll.title': 'Payroll',
    'payroll.add': 'Process Payroll',
    'payroll.create_title': 'Process Employee Payroll',
    'payroll.confirm': 'Confirm Payment',
    'payroll.processing': 'Processing...',
    'payroll.no_data': 'No payroll records found for this month.',
    'payroll.created': 'Payroll processed',
    'payroll.employee': 'Employee',
    'payroll.select_employee': 'Select employee',
    'payroll.base_salary': 'Base Salary:',
    'payroll.bonus': 'Bonus',
    'payroll.deductions': 'Deductions',
    'payroll.net_salary': 'Net Salary:',
    'payroll.basic_salary': 'Basic Salary',
    'payroll.status.paid': 'Paid',
    'payroll.processed': 'Processed:',
    // Accounting
    'accounting.title': 'Accounting',
    'accounting.add': 'Add Transaction',
    'accounting.create_title': 'New Transaction',
    'accounting.save': 'Save Transaction',
    'accounting.saving': 'Saving...',
    'accounting.search': 'Search transactions...',
    'accounting.no_data': 'No transactions found.',
    'accounting.delete_confirm': 'Are you sure you want to delete this transaction?',
    'accounting.created': 'Transaction added',
    'accounting.deleted': 'Transaction removed',
    'accounting.net_balance': 'Net Balance',
    'accounting.total_income': 'Total Income',
    'accounting.total_expenses': 'Total Expenses',
    'accounting.all_transactions': 'All Transactions',
    'accounting.income_only': 'Income Only',
    'accounting.expenses_only': 'Expenses Only',
    'accounting.type.income': 'Income',
    'accounting.type.expense': 'Expense',
    // Reports
    'reports.title': 'Business Reports',
    'reports.sales': 'Sales',
    'reports.inventory': 'Inventory',
    'reports.hr': 'HR',
    'reports.sales_performance': 'Sales Performance',
    'reports.inventory_valuation': 'Inventory Valuation',
    'reports.hr_summary': 'HR & Attendance Summary',
    'reports.total_revenue': 'Total Revenue',
    'reports.total_orders': 'Total Orders',
    'reports.avg_order_value': 'Average Order Value',
    'reports.total_items': 'Total Items',
    'reports.stock_value': 'Stock Value',
    'reports.low_stock': 'Low Stock',
    'reports.out_of_stock': 'Out of Stock',
    'reports.total_employees': 'Total Employees',
    'reports.active_staff': 'Active Staff',
    'reports.monthly_payroll': 'Monthly Payroll',
    'reports.overall_attendance': 'Overall Attendance',
    'reports.top_products': 'Top Products',
    'reports.order_distribution': 'Order Status Distribution',
    'reports.stock_by_category': 'Stock Value by Category',
    'reports.attendance_breakdown': 'Attendance Breakdown',
    'reports.staff_by_dept': 'Staff by Department',
    'reports.period.week': 'This Week',
    'reports.period.month': 'This Month',
    'reports.period.quarter': 'This Quarter',
    'reports.period.year': 'This Year',
    'reports.attendance.present': 'Present',
    'reports.attendance.absent': 'Absent',
    'reports.attendance.late': 'Late',
    'reports.attendance.half_day': 'Half Day',
  },
  bn: {
    'app.name': 'আল-ইয়ামেন বিএমএস',
    // Nav
    'nav.dashboard': 'ড্যাশবোর্ড',
    'nav.customers': 'গ্রাহক',
    'nav.sales': 'বিক্রয়',
    'nav.suppliers': 'সরবরাহকারী',
    'nav.purchases': 'ক্রয়',
    'nav.products': 'পণ্য',
    'nav.hr': 'মানব সম্পদ',
    'nav.employees': 'কর্মচারী',
    'nav.attendance': 'উপস্থিতি',
    'nav.payroll': 'বেতন',
    'nav.accounting': 'হিসাবরক্ষণ',
    'nav.reports': 'রিপোর্ট',
    'nav.logout': 'লগআউট',
    'nav.my_account': 'আমার অ্যাকাউন্ট',
    // Common
    'common.search': 'অনুসন্ধান...',
    'common.add': 'নতুন যোগ করুন',
    'common.edit': 'সম্পাদনা',
    'common.delete': 'মুছে ফেলুন',
    'common.save': 'সংরক্ষণ',
    'common.cancel': 'বাতিল',
    'common.loading': 'লোড হচ্ছে...',
    'common.actions': 'কর্ম',
    'common.saving': 'সংরক্ষণ হচ্ছে...',
    'common.name': 'নাম',
    'common.email': 'ইমেইল',
    'common.phone': 'ফোন',
    'common.address': 'ঠিকানা',
    'common.date': 'তারিখ',
    'common.status': 'অবস্থা',
    'common.notes': 'নোট',
    'common.amount': 'পরিমাণ',
    'common.total': 'মোট',
    'common.balance': 'ব্যালেন্স',
    'common.joined': 'যোগদান',
    'common.contact': 'যোগাযোগ',
    'common.success': 'সফল',
    'common.error': 'ত্রুটি',
    'common.deleted': 'মুছে ফেলা হয়েছে',
    'common.no_data': 'কোনো ডেটা পাওয়া যায়নি।',
    'common.all': 'সব',
    'common.none': '—',
    'common.description': 'বিবরণ',
    'common.category': 'বিভাগ',
    'common.type': 'ধরন',
    'common.month': 'মাস',
    'common.items': 'পণ্যসমূহ',
    'common.qty': 'পরিমাণ',
    'common.unit_price': 'একক মূল্য',
    'common.salary': 'বেতন',
    // Login
    'login.title': 'স্বাগতম',
    'login.subtitle': 'আপনার অ্যাকাউন্টে সাইন ইন করুন',
    'login.email': 'ইমেইল',
    'login.password': 'পাসওয়ার্ড',
    'login.submit': 'সাইন ইন',
    'login.logging_in': 'লগইন হচ্ছে...',
    'login.demo_accounts': 'ডেমো অ্যাকাউন্ট',
    'login.demo_admin': 'অ্যাডমিন',
    'login.demo_manager': 'ম্যানেজার',
    'login.demo_cashier': 'ক্যাশিয়ার',
    // Dashboard
    'dashboard.title': 'ড্যাশবোর্ড',
    'dashboard.total_sales': 'মোট বিক্রয়',
    'dashboard.total_purchases': 'মোট ক্রয়',
    'dashboard.total_customers': 'মোট গ্রাহক',
    'dashboard.low_stock': 'কম স্টক পণ্য',
    'dashboard.recent_activity': 'সাম্প্রতিক কার্যক্রম',
    'dashboard.monthly_overview': 'মাসিক আয় বনাম ব্যয়',
    'dashboard.revenue': 'আয়',
    'dashboard.expenses': 'ব্যয়',
    // Customers
    'customers.title': 'গ্রাহক',
    'customers.add': 'গ্রাহক যোগ করুন',
    'customers.create_title': 'নতুন গ্রাহক তৈরি করুন',
    'customers.save': 'গ্রাহক সংরক্ষণ করুন',
    'customers.search': 'গ্রাহক খুঁজুন...',
    'customers.no_data': 'কোনো গ্রাহক পাওয়া যায়নি।',
    'customers.delete_confirm': 'আপনি কি এই গ্রাহককে মুছে ফেলতে চান?',
    'customers.created': 'গ্রাহক তৈরি হয়েছে',
    'customers.deleted': 'গ্রাহক সফলভাবে মুছে ফেলা হয়েছে',
    // Suppliers
    'suppliers.title': 'সরবরাহকারী',
    'suppliers.add': 'সরবরাহকারী যোগ করুন',
    'suppliers.create_title': 'নতুন সরবরাহকারী তৈরি করুন',
    'suppliers.save': 'সরবরাহকারী সংরক্ষণ করুন',
    'suppliers.search': 'সরবরাহকারী খুঁজুন...',
    'suppliers.no_data': 'কোনো সরবরাহকারী পাওয়া যায়নি।',
    'suppliers.delete_confirm': 'আপনি কি এই সরবরাহকারীকে মুছে ফেলতে চান?',
    'suppliers.created': 'সরবরাহকারী তৈরি হয়েছে',
    'suppliers.deleted': 'সরবরাহকারী সফলভাবে মুছে ফেলা হয়েছে',
    // Sales
    'sales.title': 'বিক্রয় অর্ডার',
    'sales.add': 'নতুন বিক্রয়',
    'sales.create_title': 'বিক্রয় অর্ডার তৈরি করুন',
    'sales.complete': 'বিক্রয় সম্পন্ন করুন',
    'sales.creating': 'তৈরি হচ্ছে...',
    'sales.search': 'অর্ডার খুঁজুন...',
    'sales.no_data': 'কোনো বিক্রয় অর্ডার পাওয়া যায়নি।',
    'sales.delete_confirm': 'আপনি কি এই অর্ডারটি মুছে ফেলতে চান?',
    'sales.created': 'বিক্রয় অর্ডার তৈরি হয়েছে',
    'sales.deleted': 'বিক্রয় অর্ডার মুছে ফেলা হয়েছে',
    'sales.customer_name': 'গ্রাহকের নাম',
    'sales.discount': 'ছাড়',
    'sales.paid_amount': 'পরিশোধিত পরিমাণ',
    'sales.order_number': 'অর্ডার নং',
    'sales.customer': 'গ্রাহক',
    'sales.all_statuses': 'সব অবস্থা',
    'sales.status.pending': 'অপেক্ষমাণ',
    'sales.status.confirmed': 'নিশ্চিত',
    'sales.status.delivered': 'বিতরণ করা হয়েছে',
    'sales.status.cancelled': 'বাতিল',
    'sales.add_item': 'পণ্য যোগ করুন',
    'sales.product_id': 'পণ্য আইডি',
    // Purchases
    'purchases.title': 'ক্রয় অর্ডার',
    'purchases.add': 'নতুন ক্রয়',
    'purchases.create_title': 'ক্রয় অর্ডার তৈরি করুন',
    'purchases.create_btn': 'অর্ডার তৈরি করুন',
    'purchases.creating': 'তৈরি হচ্ছে...',
    'purchases.search': 'অর্ডার খুঁজুন...',
    'purchases.no_data': 'কোনো ক্রয় অর্ডার পাওয়া যায়নি।',
    'purchases.delete_confirm': 'আপনি কি এই অর্ডারটি মুছে ফেলতে চান?',
    'purchases.created': 'ক্রয় অর্ডার তৈরি হয়েছে',
    'purchases.deleted': 'ক্রয় অর্ডার মুছে ফেলা হয়েছে',
    'purchases.supplier_name': 'সরবরাহকারীর নাম',
    'purchases.paid_amount': 'পরিশোধিত পরিমাণ',
    'purchases.order_number': 'অর্ডার নং',
    'purchases.supplier': 'সরবরাহকারী',
    'purchases.all_statuses': 'সব অবস্থা',
    'purchases.status.pending': 'অপেক্ষমাণ',
    'purchases.status.received': 'প্রাপ্ত',
    'purchases.status.cancelled': 'বাতিল',
    'purchases.add_item': 'পণ্য যোগ করুন',
    'purchases.unit_cost': 'একক খরচ',
    // Products
    'products.title': 'পণ্য ও ইনভেন্টরি',
    'products.add': 'পণ্য যোগ করুন',
    'products.create_title': 'নতুন পণ্য তৈরি করুন',
    'products.save': 'পণ্য সংরক্ষণ করুন',
    'products.saving': 'সংরক্ষণ হচ্ছে...',
    'products.search': 'পণ্য খুঁজুন...',
    'products.no_data': 'কোনো পণ্য পাওয়া যায়নি।',
    'products.delete_confirm': 'আপনি কি এই পণ্যটি মুছে ফেলতে চান?',
    'products.created': 'পণ্য তৈরি হয়েছে',
    'products.deleted': 'পণ্য মুছে ফেলা হয়েছে',
    'products.sku': 'এসকেইউ',
    'products.unit': 'একক (যেমন পিস, কেজি, বাক্স)',
    'products.selling_price': 'বিক্রয় মূল্য',
    'products.cost_price': 'ক্রয় মূল্য',
    'products.initial_stock': 'প্রারম্ভিক স্টক',
    'products.min_stock': 'ন্যূনতম স্টক সতর্কতা স্তর',
    'products.product': 'পণ্য',
    'products.price': 'মূল্য',
    'products.stock': 'স্টক',
    'products.low': 'কম',
    // Employees
    'employees.title': 'কর্মচারী',
    'employees.add': 'কর্মচারী যোগ করুন',
    'employees.create_title': 'নতুন কর্মচারী প্রোফাইল',
    'employees.save': 'কর্মচারী সংরক্ষণ করুন',
    'employees.saving': 'সংরক্ষণ হচ্ছে...',
    'employees.search': 'কর্মচারী খুঁজুন...',
    'employees.no_data': 'কোনো কর্মচারী পাওয়া যায়নি।',
    'employees.delete_confirm': 'আপনি কি এই কর্মচারীকে মুছে ফেলতে চান?',
    'employees.created': 'কর্মচারী তৈরি হয়েছে',
    'employees.deleted': 'কর্মচারী সফলভাবে মুছে ফেলা হয়েছে',
    'employees.full_name': 'পূর্ণ নাম',
    'employees.join_date': 'যোগদানের তারিখ',
    'employees.department': 'বিভাগ',
    'employees.position': 'পদ / ভূমিকা',
    'employees.monthly_salary': 'মাসিক বেতন',
    'employees.employee': 'কর্মচারী',
    'employees.role': 'ভূমিকা',
    'employees.joined': 'যোগদান:',
    'employees.status.active': 'সক্রিয়',
    'employees.status.inactive': 'নিষ্ক্রিয়',
    // Attendance
    'attendance.title': 'উপস্থিতি',
    'attendance.add': 'উপস্থিতি চিহ্নিত করুন',
    'attendance.create_title': 'উপস্থিতি রেকর্ড করুন',
    'attendance.save': 'রেকর্ড সংরক্ষণ করুন',
    'attendance.saving': 'সংরক্ষণ হচ্ছে...',
    'attendance.no_data': 'এই মাসে কোনো উপস্থিতি রেকর্ড নেই।',
    'attendance.created': 'উপস্থিতি রেকর্ড করা হয়েছে',
    'attendance.employee': 'কর্মচারী',
    'attendance.select_employee': 'কর্মচারী নির্বাচন করুন',
    'attendance.select_status': 'অবস্থা নির্বাচন করুন',
    'attendance.check_in': 'প্রবেশের সময়',
    'attendance.check_out': 'প্রস্থানের সময়',
    'attendance.status.present': 'উপস্থিত',
    'attendance.status.absent': 'অনুপস্থিত',
    'attendance.status.late': 'দেরি',
    'attendance.status.half_day': 'অর্ধদিন',
    // Payroll
    'payroll.title': 'বেতন',
    'payroll.add': 'বেতন প্রক্রিয়া করুন',
    'payroll.create_title': 'কর্মচারীর বেতন প্রক্রিয়া করুন',
    'payroll.confirm': 'পেমেন্ট নিশ্চিত করুন',
    'payroll.processing': 'প্রক্রিয়া হচ্ছে...',
    'payroll.no_data': 'এই মাসে কোনো বেতন রেকর্ড নেই।',
    'payroll.created': 'বেতন প্রক্রিয়া হয়েছে',
    'payroll.employee': 'কর্মচারী',
    'payroll.select_employee': 'কর্মচারী নির্বাচন করুন',
    'payroll.base_salary': 'মূল বেতন:',
    'payroll.bonus': 'বোনাস',
    'payroll.deductions': 'কর্তন',
    'payroll.net_salary': 'নেট বেতন:',
    'payroll.basic_salary': 'মূল বেতন',
    'payroll.status.paid': 'পরিশোধিত',
    'payroll.processed': 'প্রক্রিয়া করা:',
    // Accounting
    'accounting.title': 'হিসাবরক্ষণ',
    'accounting.add': 'লেনদেন যোগ করুন',
    'accounting.create_title': 'নতুন লেনদেন',
    'accounting.save': 'লেনদেন সংরক্ষণ করুন',
    'accounting.saving': 'সংরক্ষণ হচ্ছে...',
    'accounting.search': 'লেনদেন খুঁজুন...',
    'accounting.no_data': 'কোনো লেনদেন পাওয়া যায়নি।',
    'accounting.delete_confirm': 'আপনি কি এই লেনদেনটি মুছে ফেলতে চান?',
    'accounting.created': 'লেনদেন যোগ করা হয়েছে',
    'accounting.deleted': 'লেনদেন মুছে ফেলা হয়েছে',
    'accounting.net_balance': 'নেট ব্যালেন্স',
    'accounting.total_income': 'মোট আয়',
    'accounting.total_expenses': 'মোট ব্যয়',
    'accounting.all_transactions': 'সব লেনদেন',
    'accounting.income_only': 'শুধু আয়',
    'accounting.expenses_only': 'শুধু ব্যয়',
    'accounting.type.income': 'আয়',
    'accounting.type.expense': 'ব্যয়',
    // Reports
    'reports.title': 'ব্যবসায়িক রিপোর্ট',
    'reports.sales': 'বিক্রয়',
    'reports.inventory': 'ইনভেন্টরি',
    'reports.hr': 'মানব সম্পদ',
    'reports.sales_performance': 'বিক্রয় কার্যক্ষমতা',
    'reports.inventory_valuation': 'ইনভেন্টরি মূল্যায়ন',
    'reports.hr_summary': 'মানব সম্পদ ও উপস্থিতি সারসংক্ষেপ',
    'reports.total_revenue': 'মোট রাজস্ব',
    'reports.total_orders': 'মোট অর্ডার',
    'reports.avg_order_value': 'গড় অর্ডার মূল্য',
    'reports.total_items': 'মোট পণ্য',
    'reports.stock_value': 'স্টকের মূল্য',
    'reports.low_stock': 'কম স্টক',
    'reports.out_of_stock': 'স্টক শেষ',
    'reports.total_employees': 'মোট কর্মচারী',
    'reports.active_staff': 'সক্রিয় কর্মী',
    'reports.monthly_payroll': 'মাসিক বেতন',
    'reports.overall_attendance': 'সামগ্রিক উপস্থিতি',
    'reports.top_products': 'শীর্ষ পণ্য',
    'reports.order_distribution': 'অর্ডার অবস্থার বিতরণ',
    'reports.stock_by_category': 'বিভাগ অনুযায়ী স্টক মূল্য',
    'reports.attendance_breakdown': 'উপস্থিতির বিশ্লেষণ',
    'reports.staff_by_dept': 'বিভাগ অনুযায়ী কর্মী',
    'reports.period.week': 'এই সপ্তাহ',
    'reports.period.month': 'এই মাস',
    'reports.period.quarter': 'এই ত্রৈমাসিক',
    'reports.period.year': 'এই বছর',
    'reports.attendance.present': 'উপস্থিত',
    'reports.attendance.absent': 'অনুপস্থিত',
    'reports.attendance.late': 'দেরি',
    'reports.attendance.half_day': 'অর্ধদিন',
  },
  ar: {
    'app.name': 'نظام إدارة اليَمَن',
    // Nav
    'nav.dashboard': 'لوحة القيادة',
    'nav.customers': 'العملاء',
    'nav.sales': 'المبيعات',
    'nav.suppliers': 'الموردين',
    'nav.purchases': 'المشتريات',
    'nav.products': 'المنتجات',
    'nav.hr': 'الموارد البشرية',
    'nav.employees': 'الموظفين',
    'nav.attendance': 'الحضور',
    'nav.payroll': 'الرواتب',
    'nav.accounting': 'المحاسبة',
    'nav.reports': 'التقارير',
    'nav.logout': 'تسجيل خروج',
    'nav.my_account': 'حسابي',
    // Common
    'common.search': 'بحث...',
    'common.add': 'إضافة جديد',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.loading': 'جاري التحميل...',
    'common.actions': 'إجراءات',
    'common.saving': 'جاري الحفظ...',
    'common.name': 'الاسم',
    'common.email': 'البريد الإلكتروني',
    'common.phone': 'الهاتف',
    'common.address': 'العنوان',
    'common.date': 'التاريخ',
    'common.status': 'الحالة',
    'common.notes': 'ملاحظات',
    'common.amount': 'المبلغ',
    'common.total': 'الإجمالي',
    'common.balance': 'الرصيد',
    'common.joined': 'تاريخ الانضمام',
    'common.contact': 'التواصل',
    'common.success': 'نجاح',
    'common.error': 'خطأ',
    'common.deleted': 'تم الحذف',
    'common.no_data': 'لا توجد بيانات.',
    'common.all': 'الكل',
    'common.none': '—',
    'common.description': 'الوصف',
    'common.category': 'الفئة',
    'common.type': 'النوع',
    'common.month': 'الشهر',
    'common.items': 'العناصر',
    'common.qty': 'الكمية',
    'common.unit_price': 'سعر الوحدة',
    'common.salary': 'الراتب',
    // Login
    'login.title': 'مرحباً بعودتك',
    'login.subtitle': 'تسجيل الدخول إلى حسابك',
    'login.email': 'البريد الإلكتروني',
    'login.password': 'كلمة المرور',
    'login.submit': 'تسجيل الدخول',
    'login.logging_in': 'جاري تسجيل الدخول...',
    'login.demo_accounts': 'حسابات تجريبية',
    'login.demo_admin': 'المدير',
    'login.demo_manager': 'المدير الإداري',
    'login.demo_cashier': 'أمين الصندوق',
    // Dashboard
    'dashboard.title': 'لوحة القيادة',
    'dashboard.total_sales': 'إجمالي المبيعات',
    'dashboard.total_purchases': 'إجمالي المشتريات',
    'dashboard.total_customers': 'إجمالي العملاء',
    'dashboard.low_stock': 'المنتجات منخفضة المخزون',
    'dashboard.recent_activity': 'النشاط الأخير',
    'dashboard.monthly_overview': 'الإيرادات الشهرية مقابل المصروفات',
    'dashboard.revenue': 'الإيرادات',
    'dashboard.expenses': 'المصروفات',
    // Customers
    'customers.title': 'العملاء',
    'customers.add': 'إضافة عميل',
    'customers.create_title': 'إنشاء عميل جديد',
    'customers.save': 'حفظ العميل',
    'customers.search': 'بحث العملاء...',
    'customers.no_data': 'لا يوجد عملاء.',
    'customers.delete_confirm': 'هل أنت متأكد من حذف هذا العميل؟',
    'customers.created': 'تم إنشاء العميل',
    'customers.deleted': 'تم حذف العميل بنجاح',
    // Suppliers
    'suppliers.title': 'الموردين',
    'suppliers.add': 'إضافة مورد',
    'suppliers.create_title': 'إنشاء مورد جديد',
    'suppliers.save': 'حفظ المورد',
    'suppliers.search': 'بحث الموردين...',
    'suppliers.no_data': 'لا يوجد موردين.',
    'suppliers.delete_confirm': 'هل أنت متأكد من حذف هذا المورد؟',
    'suppliers.created': 'تم إنشاء المورد',
    'suppliers.deleted': 'تم حذف المورد بنجاح',
    // Sales
    'sales.title': 'أوامر البيع',
    'sales.add': 'بيع جديد',
    'sales.create_title': 'إنشاء أمر بيع',
    'sales.complete': 'إتمام البيع',
    'sales.creating': 'جاري الإنشاء...',
    'sales.search': 'بحث الأوامر...',
    'sales.no_data': 'لا توجد أوامر بيع.',
    'sales.delete_confirm': 'هل أنت متأكد من حذف هذا الأمر؟',
    'sales.created': 'تم إنشاء أمر البيع',
    'sales.deleted': 'تم حذف أمر البيع',
    'sales.customer_name': 'اسم العميل',
    'sales.discount': 'الخصم',
    'sales.paid_amount': 'المبلغ المدفوع',
    'sales.order_number': 'رقم الأمر',
    'sales.customer': 'العميل',
    'sales.all_statuses': 'جميع الحالات',
    'sales.status.pending': 'معلق',
    'sales.status.confirmed': 'مؤكد',
    'sales.status.delivered': 'تم التسليم',
    'sales.status.cancelled': 'ملغى',
    'sales.add_item': 'إضافة عنصر',
    'sales.product_id': 'معرف المنتج',
    // Purchases
    'purchases.title': 'أوامر الشراء',
    'purchases.add': 'شراء جديد',
    'purchases.create_title': 'إنشاء أمر شراء',
    'purchases.create_btn': 'إنشاء الأمر',
    'purchases.creating': 'جاري الإنشاء...',
    'purchases.search': 'بحث الأوامر...',
    'purchases.no_data': 'لا توجد أوامر شراء.',
    'purchases.delete_confirm': 'هل أنت متأكد من حذف هذا الأمر؟',
    'purchases.created': 'تم إنشاء أمر الشراء',
    'purchases.deleted': 'تم حذف أمر الشراء',
    'purchases.supplier_name': 'اسم المورد',
    'purchases.paid_amount': 'المبلغ المدفوع',
    'purchases.order_number': 'رقم الأمر',
    'purchases.supplier': 'المورد',
    'purchases.all_statuses': 'جميع الحالات',
    'purchases.status.pending': 'معلق',
    'purchases.status.received': 'تم الاستلام',
    'purchases.status.cancelled': 'ملغى',
    'purchases.add_item': 'إضافة عنصر',
    'purchases.unit_cost': 'تكلفة الوحدة',
    // Products
    'products.title': 'المنتجات والمخزون',
    'products.add': 'إضافة منتج',
    'products.create_title': 'إنشاء منتج جديد',
    'products.save': 'حفظ المنتج',
    'products.saving': 'جاري الحفظ...',
    'products.search': 'بحث المنتجات...',
    'products.no_data': 'لا توجد منتجات.',
    'products.delete_confirm': 'هل أنت متأكد من حذف هذا المنتج؟',
    'products.created': 'تم إنشاء المنتج',
    'products.deleted': 'تم حذف المنتج',
    'products.sku': 'رمز المنتج',
    'products.unit': 'الوحدة (مثل قطعة، كيلو، صندوق)',
    'products.selling_price': 'سعر البيع',
    'products.cost_price': 'سعر التكلفة',
    'products.initial_stock': 'المخزون الأولي',
    'products.min_stock': 'مستوى تنبيه الحد الأدنى للمخزون',
    'products.product': 'المنتج',
    'products.price': 'السعر',
    'products.stock': 'المخزون',
    'products.low': 'منخفض',
    // Employees
    'employees.title': 'الموظفين',
    'employees.add': 'إضافة موظف',
    'employees.create_title': 'ملف موظف جديد',
    'employees.save': 'حفظ الموظف',
    'employees.saving': 'جاري الحفظ...',
    'employees.search': 'بحث الموظفين...',
    'employees.no_data': 'لا يوجد موظفين.',
    'employees.delete_confirm': 'هل أنت متأكد من حذف هذا الموظف؟',
    'employees.created': 'تم إنشاء الموظف',
    'employees.deleted': 'تم حذف الموظف بنجاح',
    'employees.full_name': 'الاسم الكامل',
    'employees.join_date': 'تاريخ الانضمام',
    'employees.department': 'القسم',
    'employees.position': 'المنصب / الدور',
    'employees.monthly_salary': 'الراتب الشهري',
    'employees.employee': 'الموظف',
    'employees.role': 'الدور',
    'employees.joined': 'انضم:',
    'employees.status.active': 'نشط',
    'employees.status.inactive': 'غير نشط',
    // Attendance
    'attendance.title': 'الحضور',
    'attendance.add': 'تسجيل الحضور',
    'attendance.create_title': 'تسجيل الحضور',
    'attendance.save': 'حفظ السجل',
    'attendance.saving': 'جاري الحفظ...',
    'attendance.no_data': 'لا توجد سجلات حضور لهذا الشهر.',
    'attendance.created': 'تم تسجيل الحضور',
    'attendance.employee': 'الموظف',
    'attendance.select_employee': 'اختر موظفاً',
    'attendance.select_status': 'اختر الحالة',
    'attendance.check_in': 'وقت الدخول',
    'attendance.check_out': 'وقت الخروج',
    'attendance.status.present': 'حاضر',
    'attendance.status.absent': 'غائب',
    'attendance.status.late': 'متأخر',
    'attendance.status.half_day': 'نصف يوم',
    // Payroll
    'payroll.title': 'الرواتب',
    'payroll.add': 'معالجة الراتب',
    'payroll.create_title': 'معالجة راتب الموظف',
    'payroll.confirm': 'تأكيد الدفع',
    'payroll.processing': 'جاري المعالجة...',
    'payroll.no_data': 'لا توجد سجلات رواتب لهذا الشهر.',
    'payroll.created': 'تمت معالجة الراتب',
    'payroll.employee': 'الموظف',
    'payroll.select_employee': 'اختر موظفاً',
    'payroll.base_salary': 'الراتب الأساسي:',
    'payroll.bonus': 'المكافأة',
    'payroll.deductions': 'الخصومات',
    'payroll.net_salary': 'صافي الراتب:',
    'payroll.basic_salary': 'الراتب الأساسي',
    'payroll.status.paid': 'مدفوع',
    'payroll.processed': 'تمت المعالجة:',
    // Accounting
    'accounting.title': 'المحاسبة',
    'accounting.add': 'إضافة معاملة',
    'accounting.create_title': 'معاملة جديدة',
    'accounting.save': 'حفظ المعاملة',
    'accounting.saving': 'جاري الحفظ...',
    'accounting.search': 'بحث المعاملات...',
    'accounting.no_data': 'لا توجد معاملات.',
    'accounting.delete_confirm': 'هل أنت متأكد من حذف هذه المعاملة؟',
    'accounting.created': 'تمت إضافة المعاملة',
    'accounting.deleted': 'تم حذف المعاملة',
    'accounting.net_balance': 'صافي الرصيد',
    'accounting.total_income': 'إجمالي الإيرادات',
    'accounting.total_expenses': 'إجمالي المصروفات',
    'accounting.all_transactions': 'جميع المعاملات',
    'accounting.income_only': 'الإيرادات فقط',
    'accounting.expenses_only': 'المصروفات فقط',
    'accounting.type.income': 'إيراد',
    'accounting.type.expense': 'مصروف',
    // Reports
    'reports.title': 'تقارير الأعمال',
    'reports.sales': 'المبيعات',
    'reports.inventory': 'المخزون',
    'reports.hr': 'الموارد البشرية',
    'reports.sales_performance': 'أداء المبيعات',
    'reports.inventory_valuation': 'تقييم المخزون',
    'reports.hr_summary': 'ملخص الموارد البشرية والحضور',
    'reports.total_revenue': 'إجمالي الإيرادات',
    'reports.total_orders': 'إجمالي الطلبات',
    'reports.avg_order_value': 'متوسط قيمة الطلب',
    'reports.total_items': 'إجمالي العناصر',
    'reports.stock_value': 'قيمة المخزون',
    'reports.low_stock': 'مخزون منخفض',
    'reports.out_of_stock': 'نفاد المخزون',
    'reports.total_employees': 'إجمالي الموظفين',
    'reports.active_staff': 'الموظفون النشطون',
    'reports.monthly_payroll': 'كشف الرواتب الشهري',
    'reports.overall_attendance': 'الحضور الإجمالي',
    'reports.top_products': 'أفضل المنتجات',
    'reports.order_distribution': 'توزيع حالات الطلبات',
    'reports.stock_by_category': 'قيمة المخزون حسب الفئة',
    'reports.attendance_breakdown': 'تفصيل الحضور',
    'reports.staff_by_dept': 'الموظفون حسب القسم',
    'reports.period.week': 'هذا الأسبوع',
    'reports.period.month': 'هذا الشهر',
    'reports.period.quarter': 'هذا الربع',
    'reports.period.year': 'هذا العام',
    'reports.attendance.present': 'حاضر',
    'reports.attendance.absent': 'غائب',
    'reports.attendance.late': 'متأخر',
    'reports.attendance.half_day': 'نصف يوم',
  }
};

export const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(
    (localStorage.getItem('al-yamen-lang') as Language) || 'en'
  );

  const setLanguage = (lang: Language) => {
    localStorage.setItem('al-yamen-lang', lang);
    setLanguageState(lang);
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  };

  useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return React.createElement(LanguageContext.Provider, { value: { language, setLanguage, t } }, children);
}

export function useLanguage(): LanguageContextType {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
