[[pages]]
path = "/"
screenshotTimestamp = "2026-04-08T21:42:49Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/31fb95bb-09bb-49a5-9c6c-9b4cafc985ac/febf6e64-df67-479a-a719-a8910a34b9c7/LK82tWU"

[[pages]]
path = "/login"
screenshotTimestamp = "2026-04-07T09:00:20Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/09c966ef-65d7-4d59-bd65-6154de931cfb/a65656bd-dd1a-495b-8953-77053fbdc948/nPllNv5"

[[pages]]
path = "/dashboard"
screenshotTimestamp = "2026-04-07T08:59:58Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/09c966ef-65d7-4d59-bd65-6154de931cfb/a65656bd-dd1a-495b-8953-77053fbdc948/XxeN26Z"
